Feature - Notification unveil
hyperoslo/Whisper pull request #108
Opened 2016-07-30 22:05 UTC by tkohout

I have added new feature to unveil rest of the notification if it doesn't fit. Additionally I enlarged the gestureContainer to the whole area of notification. It does work similar as the apple system notifications. 

Preview:

![whisper-unveil2](https://cloud.githubusercontent.com/assets/3404675/17273353/cc0a0084-56b1-11e6-8ae7-f39189381c6d.gif)

2016-09-27 06:59 UTC, zenangst requested changes
I think this looks good, just made a few comments about some minor stuff that we probably want to fix up before merging.

2016-09-27 06:59 UTC, zenangst commented on Source/ShoutFactory.swift
> +
Could you go ahead and remove this whitespace? 😁

2016-09-27 06:59 UTC, zenangst commented on Source/ShoutFactory.swift
> +  var subtitleLabelOriginalHeight: CGFloat = 0
You should probably have this `var` at the top of the file instead of in between method declarations.

2016-09-27 06:59 UTC, zenangst commented on Source/ShoutFactory.swift
> +      self.subtitleLabel.sizeToFit()
Do you need to reference `self` here?

2016-09-27 06:59 UTC, zenangst commented on Source/ShoutFactory.swift
> +      self.subtitleLabel.sizeToFit()
You can probably drop `self` here as well.

2016-09-29 10:35 UTC, tkohout commented
Thanks for the reply,
I've used https://github.com/hyperoslo/Whisper/pull/102 as a base for this feature and I've recently noticed some problems when the shout layout is reloaded.

I will send fixes for this and mentioned minor stuff over the weekend.

Cheers
Tomas

2016-10-01 16:09 UTC, tkohout commented
Done. I added the required changes and fixed the issue with the orientation change.

2016-10-02 09:41 UTC, zenangst approved these changes

2016-10-02 09:43 UTC, merged

2016-10-02 09:44 UTC, zenangst commented
@tkohout thanks mate, this is great!

![unknown-9](https://cloud.githubusercontent.com/assets/57446/19019848/8039d4de-8895-11e6-9321-90132a307005.gif)